### ISSUE TITLE
Doesn't work with Budgie 10.3.1

### ISSUE THREAD

**Issue by LinuxJedi** [jonathan-j-lee/caffeine#1]
I'm using Budgie 10.3.1 on the latest Solus. I've followed the README but it isn't showing as a possible plugin in Raven, even after a reboot.

Am I doing something wrong or has the plugin API changed a bit?

**Comment by jonathan-j-lee** [comment]
I believe the Budgie API has changed. The plugin broke on my machine as well a few months ago. Going to look into fixing this soon. Thanks for bringing this up.

**Comment by LinuxJedi** [comment]
Today's 142 release of budgie 10.3.1 suddenly fixed it! It is now usable again, although I recommend updating the instructions to install into a subdirectory of /usr/lib/budgie-desktop/plugins/

**Comment by jonathan-j-lee** [comment]
Updated instructions (71a5d6dc3017e9efbe16d91464e1182fb8b008b4).
